version: '3.2'

services:
  app:
    image: node:${node_version}${node_variant_dev}
    command: sh -c 'cd /app && ${NODE_BIN:-node} index.js'
    ports:
      - '8080:8080'
      - '9229:9229'   # Debugger
    volumes:
      - ./server:/app
      - ./client:/app/client
    environment:
      NODE_ENV: development
      #VUE_APP_SINGLEBOARD_MODE: 0
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
